# Note:
# Make sure that the github pages is already set to Github Actions, otherwise the workflow will fail.
#
# Author: Shubham Gupta
# GitHub: https://github.com/shubham-gupta-16/
# Created On: 5 Aug, 2022
# Updated On: 18 May, 2024

name: deploy_flutter_web
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  flutter_web_deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
# If you want to change the directory to run commands
#    defaults:
#      run:
#        working-directory: ./sub-folder
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version-file: pubspec.yaml
#          flutter-version: '3.3.10'  // uncomment this line if you want to use a specific version of Flutter
      - run: flutter pub get
      - run: flutter build web --base-href /${{ github.event.repository.name }}/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web-build
#          path: sub-folder/build/web // if working-directory is changed
          path: build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
